[package]
name = "zerocast_platform"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"

[features]
default = ["capture"]
capture = ["dep:scrap"]

[target.'cfg(any(windows, target_os = "macos", target_os = "linux"))'.dependencies]
scrap = { version = "0.5", optional = true }
