[package]
name = "zerocast_desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zerocast_core = { path = "../../crates/core" }
zerocast_transport = { path = "../../crates/transport" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
anyhow = "1.0"
